baseURL = ""
languageCode = "cs"

title = "Společně a digitálně"

disableKinds = ["section", "RSS", "sitemap", "taxonomy", "term", "taxonomyTerm"]
googleAnalytics = "G-JWD6WL94GS"

[params]
description = "Platforma neziskových organizací za digitální transformaci státu"
email = "info@spolecneadigitalne.cz"

[imaging]
quality = 90
